/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaatm;

public class App {

    public static void main(String[] args) {

        Costumer costumer = new Costumer("Bob Lasar");
        // Atm atm = new Atm(costumer);

        Bank bank = new Bank();
    }
}
