/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaatm;

import java.util.List;

public class App {

    public static void main(String[] args) {

        Bank bank = new Bank();
        Costumer loggedInCostumer = bank.getCostumer("Bob");

        Atm atm = new Atm(loggedInCostumer);
    }
}
