/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javaatm;

public class App {

    public static void main(String[] args) {

        Bank bank = new Bank();
        bank.run();
        Costumer loggedInCostumer = bank.getCostumer("Bob");

        Atm atm = new Atm();
        atm.run(loggedInCostumer);
    }
}
